name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:

  security:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2

      - name: Validate Website
        run: |
          echo "Security Passed"
          cat index.html
